### ISSUE TITLE
Question regarding svg load Firefox for similar implementation

### ISSUE THREAD

**Issue by jacksongoode** [janaSunrise/spotify-playing-readme#2]
I've had this weird, weird bug and I thought I'd bring it up as I can't find any details about it anywhere else.

I've forked your repo and made some simplifications/style edits. But perhaps somewhere along the way, I made a change I shouldn't have (?). I'm currently experiencing an odd bug where the cover of the base64 encoded cover art will only load when the mouse hovers over it.

When this happens it appears instantly, suggesting this isn't an issue with the resource being loaded on the page but something about how the svg is rendered on the page. I only experience this issue with Firefox and I can't always reproduce it. My gut tells me it might be something to do with the Vercel instance going dormant when it's not been activated in a while and so the svg isn't loaded at once with the cover image?

Here is a short little screen recording so you can get the idea.

https://user-images.githubusercontent.com/54308792/176357506-7731b2da-d857-4dc0-b5f1-1345d76157a0.mov

**Comment by janaSunrise** [comment]
Hey there- super sorry for the late reply. I'm not sure why it happens on hover, because personally I'm using firefox too, and I've checked that it works fine as intended. Maybe, it was a native issue, and has been fixed
![Peek 2022-07-31 00-20](https://user-images.githubusercontent.com/56873669/181937605-443c213f-d027-4f01-bca5-220fe7411974.gif)
.

**Comment by jacksongoode** [comment]
Huh yeah, weird. Thanks!
